const ROLE_RETAILER = 'RETAILER';
const ROLE_CUSTOMER = 'CUSTOMER';
const ROLE_SALES_REP = 'SALES REP';
const ROLE_ADMIN = 'ADMIN';
// Export defined constants
export { ROLE_RETAILER, ROLE_CUSTOMER, ROLE_SALES_REP, ROLE_ADMIN };
